# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: java:8

build1:
  stage: build
  script:
    - ./gradlew assemble
   
test1:
  stage: test
  script: 
    - bash <(curl -s https://blackducksoftware.github.io/hub-detect/hub-detect.sh) --blackduck.hub.url="https://bd-imp-eval17.blackducksoftware.com/" --blackduck.hub.username="a.popa@accenture.com" --blackduck.hub.password="blackduck"
